export const activityTypes = {
    ACTIVITY_REQUEST : 'ACTIVITY_REQUEST',
    ACTIVITY_SUCCESS : 'ACTIVITY_SUCCESS',
    ACTIVITY_FAILURE : 'ACTIVITY_FAILURE',

    DEL_ACTIVITY_REQUEST : 'DEL_ACTIVITY_REQUEST',
    DEL_ACTIVITY_SUCCESS : 'DEL_ACTIVITY_SUCCESS',
    DEL_ACTIVITY_FAILURE : 'DEL_ACTIVITY_FAILURE',

    UPDATE_ACTIVITY_REQUEST : 'UPDATE_ACTIVITY_REQUEST',
    UPDATE_ACTIVITY_SUCCESS : 'UPDATE_ACTIVITY_SUCCESS',
    UPDATE_ACTIVITY_FAILURE : 'UPDATE_ACTIVITY_FAILURE'
};
