export const checkTypes = {
    CHECKIN_REQUEST: 'CHECKIN_REQUEST',
    CHECKIN_SUCCESS: 'CHECKIN_SUCCESS',
    CHECKIN_FAILURE: 'CHECKIN_FAILURE',

    GETCHECKIN_REQUEST: 'CHECKIN_GETCHECKIN_REQUEST',
    GETCHECKIN_SUCCESS: 'CHECKIN_GETCHECKIN_SUCCESS',
    GETCHECKIN_FAILURE: 'CHECKIN_GETCHECKIN_FAILURE',

    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',


};
