export const checkTypes = {
    CHECKIN_REQUEST: 'CHECKIN_REQUEST',
    CHECKIN_SUCCESS: 'CHECKIN_SUCCESS',
    CHECKIN_FAILURE: 'CHECKIN_FAILURE',

    GETCHECKIN_REQUEST: 'CHECKIN_GETCHECKIN_REQUEST',
    GETCHECKIN_SUCCESS: 'CHECKIN_GETCHECKIN_SUCCESS',
    GETCHECKIN_FAILURE: 'CHECKIN_GETCHECKIN_FAILURE',

    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',

    // LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    // LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    // LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    // LOGOUT: 'USERS_LOGOUT',

    // GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    // GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    // GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};
