export const postsTypes = {
    GETPOSTS_REQUEST: 'POSTS_GETPOSTS_REQUEST',
    GETPOSTS_SUCCESS: 'POSTS_GETPOSTS_SUCCESS',
    GETPOSTS_FAILURE: 'POSTS_GETPOSTS_FAILURE',

    POSTPOSTS_REQUEST: 'POSTS_POSTPOSTS_REQUEST',
    POSTPOSTS_SUCCESS: 'POSTS_POSTPOSTS_SUCCESS',
    POSTPOSTS_FAILURE: 'POSTS_POSTPOSTS_FAILURE',

    // LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    // LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    // LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    // LOGOUT: 'USERS_LOGOUT',

    // GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    // GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    // GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};
