export const postsTypes = {
    GETPOSTS_REQUEST: 'POSTS_GETPOSTS_REQUEST',
    GETPOSTS_SUCCESS: 'POSTS_GETPOSTS_SUCCESS',
    GETPOSTS_FAILURE: 'POSTS_GETPOSTS_FAILURE',

    POSTPOSTS_REQUEST: 'POSTS_POSTPOSTS_REQUEST',
    POSTPOSTS_SUCCESS: 'POSTS_POSTPOSTS_SUCCESS',
    POSTPOSTS_FAILURE: 'POSTS_POSTPOSTS_FAILURE',
 
};
