export const storiesTypes = {
    GETSTORIES_REQUEST: 'STORIES_GETSTORIES_REQUEST',
    GETSTORIES_SUCCESS: 'STORIES_GETSTORIES_SUCCESS',
    GETSTORIES_FAILURE: 'STORIES_GETSTORIES_FAILURE',

    POSTSTORIES_REQUEST: 'STORIES_POSTSTORIES_REQUEST',
    POSTSTORIES_SUCCESS: 'STORIES_POSTSTORIES_SUCCESS',
    POSTSTORIES_FAILURE: 'STORIES_POSTSTORIES_FAILURE',

    // LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    // LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    // LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    // LOGOUT: 'USERS_LOGOUT',

    // GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    // GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    // GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};
