export const storiesTypes = {
    GETSTORIES_REQUEST: 'STORIES_GETSTORIES_REQUEST',
    GETSTORIES_SUCCESS: 'STORIES_GETSTORIES_SUCCESS',
    GETSTORIES_FAILURE: 'STORIES_GETSTORIES_FAILURE',

    POSTSTORIES_REQUEST: 'STORIES_POSTSTORIES_REQUEST',
    POSTSTORIES_SUCCESS: 'STORIES_POSTSTORIES_SUCCESS',
    POSTSTORIES_FAILURE: 'STORIES_POSTSTORIES_FAILURE',

};
