export const userTypes = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

    
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    PROFILECHANGE_REQUEST: 'USERS_PROFILECHANGE_REQUEST',
    PROFILECHANGE_SUCCESS: 'USERS_PROFILECHANGE_SUCCESS',
    PROFILECHANGE_FAILURE: 'USERS_PROFILECHANGE_FAILURE',

    GETUSER_REQUEST: 'USERS_GETUSER_REQUEST',
    GETUSER_SUCCESS: 'USERS_GETUSER_SUCCESS',
    GETUSER_FAILURE: 'USERS_GETUSER_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',   
    
    CHANGEPASSWORD_REQUEST: 'USERS_CHANGEPASSWORD_REQUEST',
    CHANGEPASSWORD_SUCCESS: 'USERS_CHANGEPASSWORD_SUCCESS',
    CHANGEPASSWORD_FAILURE: 'USERS_CHANGEPASSWORD_FAILURE'  
};
